ElectronicJournal.Web/Pages/CourseEdit.cshtml.cs
using ElectronicJournal.Web.Models;
using ElectronicJournal.Web.Repositories.Interfaces;
using ElectronicJournal.Web.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectronicJournal.Web.Pages
{
    public class CourseEditModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly IGroupRepository _groupRepository;
        private readonly IUserGroupRepository _userGroupRepository;
        private readonly ICourseRepository _courseRepository;
        private readonly IUserCourseRepository _userCourseRepository;

        public CourseEditModel(UserManager<User> userManager,IGroupRepository groupRepository, IUserGroupRepository userGroupRepository, ICourseRepository courseRepository, IUserCourseRepository userCourseRepository)
        {
            _userManager = userManager;
            _groupRepository = groupRepository;
            _userGroupRepository = userGroupRepository;
            _courseRepository = courseRepository;
            _userCourseRepository = userCourseRepository;
        }
        public PagingInfo usersPagingInfo { get; set; }
        public PagingInfo groupsPagingInfo { get; set; }
        public Guid UserIdAdd { get; set; }
        public Course Course { get; set; }
        public IEnumerable<UserCourse> Users { get; set; }
        public IEnumerable<Group> Groups { get; set; }
        public IEnumerable<User> NotInCourseUsers { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(Guid courseId, int currentPageGroups = 1, int currentPageUsers = 1, int pageSize = 5, string returnUrl = "/")
        {
            PrefillDataAsync(courseId, currentPageUsers: currentPageUsers, pageSize: pageSize);
        }


        public void OnPostUsers(Guid courseId, int currentPageGroups = 1, int currentPageUsers = 1, int pageSize = 5)
        {
            PrefillDataAsync(courseId, currentPageUsers: currentPageUsers, pageSize: pageSize);
        }
        public void OnPostGroups(Guid courseId, int currentPageGroups = 1, int currentPageUsers = 1, int pageSize = 5)
        {
            PrefillDataAsync(courseId, currentPageGroups: currentPageGroups, pageSize: pageSize);
        }

        public async void OnPostRemove(Guid userId, Guid courseId, int currentPageGroups = 1, int currentPageUsers = 1, int pageSize = 5)
        {
            _userCourseRepository.DeleteUser(userId, courseId);
            PrefillDataAsync(courseId, currentPageUsers: currentPageUsers, pageSize: pageSize);
        }
        public async void OnPostAddUserAsync(string username, Guid courseId, int currentPageGroups = 1, int currentPageUsers = 1, int pageSize = 5)
        {
            var user =  _userManager.Users.Where(p=>p.Name == username).First();

            UserCourse userCourse = new UserCourse()
            {
                Id = new Guid(),
                UserId = user.Id,
                CourseId = courseId,
                StatusId = 1,
            };
            _userCourseRepository.CreateAsync(userCourse);

            PrefillDataAsync(courseId, currentPageUsers: currentPageUsers,pageSize: pageSize);
        }
        private void  PrefillDataAsync(Guid courseId, int currentPageGroups=1, int currentPageUsers=1, int pageSize=5, string returnUrl = "/")
        {
            Groups = new List<Group>(10);
            Course = _courseRepository.GetByIdAsync(courseId).Result;
            usersPagingInfo = new PagingInfo()
            {
                CurrentPage = currentPageUsers,
                ItemsPerPage = pageSize,
                TotalItems = Course.UserCourses.Count,
            };

            Users = Course.UserCourses
                .Where(p =>
                {
                    return p.CourseId == courseId;
                })
                .OrderBy(p => p.Id)
                .Skip((currentPageUsers - 1) * pageSize)
                .Take(pageSize);
            var usergroups =  _userGroupRepository.GetAsync().Result;
            var userid = Course.UserCourses
                .Where(p =>
                {
                    return p.CourseId == courseId;
                }).Select(e => e.UserId);
            var groupsid = usergroups.Where(e => userid.Contains(e.UserId)).Select(e => e.Group.Id).Distinct();
            Groups =  _groupRepository.GetByCriteriaAsync(e => groupsid.Contains(e.Id)).Result.OrderBy(p => p.Id)
                .Skip((currentPageGroups - 1) * pageSize)
                .Take(pageSize); 
            groupsPagingInfo = new PagingInfo()
            {
                CurrentPage = currentPageGroups,
                ItemsPerPage = pageSize,
                TotalItems = Groups.Count(),
            };
            ReturnUrl = returnUrl ?? "/";
            var usercoursids = Course.UserCourses.Select(e => e.UserId).ToArray();
            NotInCourseUsers = _userManager.Users.Where(p => !usercoursids.Contains(p.Id)).ToArray();

        }

    }
}

ElectronicJournal.Web/Pages/CreateCourse.cshtml.cs
using ElectronicJournal.Web.Models;
using ElectronicJournal.Web.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ElectronicJournal.Web.Pages
{
    public class CreateCourseModel : PageModel
    {
        private readonly ICourseRepository _repo;
        public Course CourseRequest;
        public CreateCourseModel(ICourseRepository repo)
        {
            CourseRequest = new Course();
            _repo = repo;
        }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public void OnPost()
        {

        }
    }
}

ElectronicJournal.Web/Pages/CourseEdit.cshtml
@page
@model ElectronicJournal.Web.Pages.CourseEditModel
@{
}
<div class="text-center">
    <input type="hidden" asp-for="Course.Id" />

    <div class="form-group">
        <label asp-for="Course.Created" class="control-label">Дата создания:</label>
        <input type="date" disabled asp-for="Course.Created" class="form-control disabled" />
    </div>
    <div class="form-group">
        <label asp-for="Course.Updated" class="control-label">Дата последнего обновления:</label>
        <input type="date" disabled asp-for="Course.Updated" class="form-control disabled" />
    </div>
    <div class="form-group">
        <label asp-for="Course.Name" class="control-label">Название курса</label>
        <input asp-for="Course.Name" disabled class="form-control disabled" />
    </div>
    <div class="form-group">
        <label asp-for="Course.Description" class="control-label">Описание курса</label>
        <input asp-for="Course.Description" disabled class="form-control disabled" />
    </div>
    <div class="form-group">
        <label asp-for="Course.Type.Name" class="control-label">Тип курса</label>
        <label asp-for="Course.Type.Name" class="form-control disabled">@Model.Course.Type.Name</label>
    </div>
    @if (@Model.NotInCourseUsers.Any())
    {
        <div class="text-center">
            <form asp-page-handler="AddUser" method="post">
                <input type="search" list="datalistusers" id="searchid" name="userName" placeholder="Введите имя.." />
                <input hidden id="courseid" name="courseid" value="@Model.Course.Id" />
                <button type="submit" class="btn btn-primary">
                    Добавить
                </button>
                <datalist id="datalistusers">
                    @foreach (var user in @Model.NotInCourseUsers)
                    {
                        <option>@user.Name</option>
                    }
                </datalist>
            </form>
        </div>
    }
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Сотрудник</th>
                <th class="text-right">Статус</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var userCourse in Model.Users)
            {
                <tr>
                    <td class="text-center">@userCourse.UserId</td>
                    <td class="text-left">@userCourse.User.Name</td>
                    <td class="text-right">@userCourse.Status.StatusName</td>
                    <td class="text-center">
                        <form asp-page-handler="Remove" method="post">
                            <input type="hidden" name="userId" value="@userCourse.UserId" />
                            <input hidden id="courseid" name="courseid" value="@Model.Course.Id" />
                            <button type="submit" class="btn small btn-danger">
                                Удалить
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="d-flex justify-content-around">
        @if (Model.usersPagingInfo.CurrentPage != 1)
        {
            <form asp-page-handler="Users" method="post">
                <input type="hidden" name="currentPageUsers" value="@Model.usersPagingInfo.PreviousPage" />
                <input type="hidden" name="courseId" value="@Model.Course.Id" />
                <button type="submit" class="btn small btn-primary">
                    Предыдущая страница
                </button>
            </form>
        }
        @if (Model.usersPagingInfo.CurrentPage < Model.usersPagingInfo.TotalPages)
        {
            <form asp-page-handler="Users" method="post">
                <input type="hidden" name="currentPageUsers" value="@Model.usersPagingInfo.NextPage" />
                <input type="hidden" name="courseId" value="@Model.Course.Id" />
                <button type="submit" class="btn small btn-primary">
                    Следующая страница
                </button>
            </form>
        }
    </div>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Группа</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var userGroup in Model.Groups)
            {
                <tr>
                    <td class="text-center">@userGroup.Id</td>
                    <td class="text-left">@userGroup.Name</td>
                    <td class="text-center">
                        <form asp-page-handler="Remove" method="post">
                            <input type="hidden" name="groupId" value="@userGroup.Id" />
                            <input hidden id="courseid" name="courseid" value="@Model.Course.Id" />
                            <button type="submit" class="btn small btn-danger">
                                Удалить
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="d-flex justify-content-around">
        @if (Model.groupsPagingInfo.CurrentPage != 1)
        {
            <form asp-page-handler="Groups" method="post">
                <input type="hidden" name="currentPageGroups" value="@Model.groupsPagingInfo.PreviousPage" />
                <input type="hidden" name="courseId" value="@Model.Course.Id" />
                <button type="submit" class="btn small btn-primary">
                    Предыдущая страница
                </button>
            </form>
        }
        @if (Model.groupsPagingInfo.CurrentPage < Model.groupsPagingInfo.TotalPages)
        {
            <form asp-page-handler="Groups" method="post">
                <input type="hidden" name="currentPageGroups" value="@Model.groupsPagingInfo.NextPage" />
                <input type="hidden" name="courseId" value="@Model.Course.Id" />
                <button type="submit" class="btn small btn-primary">
                    Следующая страница
                </button>
            </form>
        }
    </div>
</div>

ElectronicJournal.Web/Pages/CreateCourse.cshtml
@page
@model ElectronicJournal.Web.Pages.CreateCourseModel
@{
}


<form asp-action="Create" asp>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <div class="form-group">
            <input hidden asp-for="CourseRequest.Id" class="control-label" />
        </div>
        <div class="form-group">
            <label asp-for="CourseRequest.Name"></label><br />
            <input asp-for="CourseRequest.Name" />
            <span asp-validation-for="CourseRequest.Name"></span>
        </div>
        <div class="form-group">
            <label asp-for="CourseRequest.Description"></label><br />
            <textarea asp-for="CourseRequest.Description">

            </textarea>
            <span asp-validation-for="CourseRequest.Description"></span>
        </div>
        <div class="form-check">
            <input name="courseType" type="radio" value="1" />
            <span>Внешний</span> <br />
            <input checked="checked" name="courseType" type="radio" value="2" />
            <span>Внутренний</span>
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="Создать" class="btn btn-primary" />
    </div>
</form>